/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Archivo;

import javax.swing.JFileChooser;

/**
 *
 * @author alum_tes_a
 */
public class CarArc extends javax.swing.JInternalFrame {

    /**
     * Creates new form CarArc2
     */
    public CarArc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAr = new javax.swing.JTextField();
        buExa = new javax.swing.JButton();
        buPro = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Abrir XML");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Archivo:");

        buExa.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buExa.setText("...");
        buExa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buExaActionPerformed(evt);
            }
        });

        buPro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buPro.setMnemonic('p');
        buPro.setText("Procesar");
        buPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buPro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAr, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buExa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buExa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(buPro)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buExaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buExaActionPerformed
        String strArc;//archivo a elegir
        JFileChooser objFilCho=new JFileChooser();
        objFilCho.setDialogTitle("Cargar");
        objFilCho.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //        objFilCho.setCurrentDirectory(new File("C:\\"));

            if (objFilCho.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
            {
                strArc=objFilCho.getSelectedFile().getPath();
            }
    }//GEN-LAST:event_buExaActionPerformed

    private void buProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buProActionPerformed
        
    }//GEN-LAST:event_buProActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buExa;
    private javax.swing.JButton buPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAr;
    // End of variables declaration//GEN-END:variables
}
