/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Archivo;
import static configuracion.Configuracion.checkTags;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author Ronald
 */
public class ProPanEti1 extends FrameImagen {

    public static List<JCheckBox> checkTags = new ArrayList<>();
    public static List<String> strTags = new ArrayList<>();
    private boolean blnAce;
    
    /**
     * Creates new form MenBusPro
     */
    public ProPanEti1() {
        initComponents();
         checkEtiquetasXml();
         Panel.requestFocus();
         
         blnAce=false;
        setImage("/imagenes/factura-electrónica5.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotConfPro = new javax.swing.ButtonGroup();
        ProGuaCa = new javax.swing.JButton();
        ProCanCa = new javax.swing.JButton();
        ProDesCa = new javax.swing.JButton();
        ProConfUno = new javax.swing.JRadioButton();
        ProConfDos = new javax.swing.JRadioButton();
        ProEliConf = new javax.swing.JButton();
        ProGuaConf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PanelConf = new javax.swing.JPanel();
        AgrProBot = new javax.swing.JToggleButton();
        QuiProBot = new javax.swing.JToggleButton();
        MarTodBot = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Propiedades Pantalla");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tes.jpg"))); // NOI18N
        setVisible(false);

        ProGuaCa.setText("Guardar");

        ProCanCa.setText("Cancelar");

        ProDesCa.setText("Descartar");

        BotConfPro.add(ProConfUno);
        ProConfUno.setForeground(new java.awt.Color(255, 255, 255));
        ProConfUno.setSelected(true);
        ProConfUno.setText("Configuración 1");

        BotConfPro.add(ProConfDos);
        ProConfDos.setForeground(new java.awt.Color(255, 255, 255));
        ProConfDos.setText("Configuración 2");

        ProEliConf.setText("Eliminar Configuración");

        ProGuaConf.setText("Guardar Configuración");

        Panel.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(Panel);

        PanelConf.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane4.setViewportView(PanelConf);

        AgrProBot.setText("Agregar");

        QuiProBot.setText("Quitar");

        MarTodBot.setText("Marcar Todo");
        MarTodBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarTodBotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProConfUno)
                    .addComponent(ProConfDos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProGuaConf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProEliConf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(177, 177, 177))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(MarTodBot, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgrProBot, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuiProBot, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProDesCa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProGuaCa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProCanCa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(ProGuaCa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(ProDesCa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(ProCanCa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(AgrProBot, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(QuiProBot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(MarTodBot, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProConfUno)
                    .addComponent(ProGuaConf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProConfDos)
                    .addComponent(ProEliConf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getAccessibleContext().setAccessibleDescription("Escoja la Propiedad que Necesite");

        setBounds(0, 0, 700, 425);
    }// </editor-fold>//GEN-END:initComponents

    private void ProConfUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProConfUnoActionPerformed

    }//GEN-LAST:event_ProConfUnoActionPerformed

    private void MarTodBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarTodBotActionPerformed
  if(MarTodBot.isSelected()){
        for(int i=0; i<checkTags.size(); i++)
        {
          MarTodBot.setText("Marcar Todo");
        checkTags.get(i).setSelected(true);
        }
        } else{
        
        for(int i=0; i<checkTags.size(); i++)
        {
        MarTodBot.setText("Marcar Todo");
        checkTags.get(i).setSelected(false);
        }
        }
    }//GEN-LAST:event_MarTodBotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AgrProBot;
    private javax.swing.ButtonGroup BotConfPro;
    private javax.swing.JToggleButton MarTodBot;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel PanelConf;
    private javax.swing.JButton ProCanCa;
    private javax.swing.JRadioButton ProConfDos;
    private javax.swing.JRadioButton ProConfUno;
    private javax.swing.JButton ProDesCa;
    private javax.swing.JButton ProEliConf;
    private javax.swing.JButton ProGuaCa;
    private javax.swing.JButton ProGuaConf;
    private javax.swing.JToggleButton QuiProBot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
 
    private void checkEtiquetasXml() 
    {
        try
        {
            File xmlDocument = new File("factura.xml"); //Crea el objeto directorio de tipo File a partir del valor de pathname.
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document document = builder.parse(xmlDocument);
            NodeList nodeList = document.getElementsByTagName("*");

            checkTags.clear();      //Limpiamos la lista 
            for (int i = 0; i < nodeList.getLength(); i++)         
            { 
                
                JCheckBox jCheckBox= new JCheckBox(nodeList.item(i).getNodeName());
                checkTags.add(jCheckBox);
                Panel.add(jCheckBox).revalidate();

            }
     
        }
            catch (IOException e) 
        {
         System.out.println("IOException " + e.getMessage());
        } 
        catch (ParserConfigurationException e) 
        {
         System.out.println("ParserConfigurationException " + e.getMessage());
        } 
        catch (SAXException e) 
        {
         System.out.println("SAXException " + e.getMessage());
        }

    }
    
    private void etiquetasSel(){
        strTags.clear();
        for (JCheckBox checkBox : checkTags) {
            if (checkBox.isSelected()) {
                strTags.add(checkBox.getText());
            }
        }
    }
   

}
